
function throwErrors() {
  throw new ReferenceError('ReferenceError');
}
const errorName = 'ReferenceError';
export {
  throwErrors,
  errorName,
};
